# Generated by Django 5.0.4 on 2024-05-01 02:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_about_content_en_about_content_ru_about_content_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authors_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='authors_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='authors_uz',
        ),
        migrations.AddField(
            model_name='editorial',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='editorial',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='editorial',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
