# Generated by Django 5.0.4 on 2024-05-01 02:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_about_author_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingarticle',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='sendingarticle',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='sendingarticle',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
