# Generated by Django 5.0.4 on 2024-05-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_sendingarticle_content_en_sendingarticle_content_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='journal_name_en',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='journal_name_ru',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='journal_name_uz',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
